app/urls.py
from django.urls import path

from app import views
from app.views import IndexView, DetailView

app_name = "app"  # htmlからURLを生成する時に使う名前空間

urlpatterns = [
    # 書籍
    path("books/", IndexView.as_view(), name="book_list"),  # 一覧
    # path("books/", views.book_list, name="book_list"),  # 一覧
    path("books/detail/<int:pk>/", DetailView.as_view(), name="book_detail"),  # 詳細
    path("books/add/", views.book_edit, name="book_add"),  # 登録
    path("books/mod/<int:book_id>/", views.book_edit, name="book_edit"),  # 修正
    path("books/del/<int:book_id>/", views.book_del, name="book_del"),  # 削除
    # other
    path("other", views.other, name="other"),
]

django_poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("app/", include("app.urls"))]

app/models.py
from django.db import models


class Book(models.Model):
    """書籍"""

    name = models.CharField("書籍名", max_length=255)
    publisher = models.CharField("出版社", max_length=255, blank=True)
    page = models.IntegerField("ページ数", blank=True, default=0)

    def __str__(self):
        return self.name + ": 文字列です"


class Impression(models.Model):
    """感想"""

    book = models.ForeignKey(
        Book, verbose_name="書籍", related_name="impressions", on_delete=models.CASCADE
    )
    comment = models.TextField("コメント", blank=True)

    def __str__(self):
        return self.comment + ": 文字列です"

app/forms.py
from django.forms import ModelForm

from app.models import Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ("name", "publisher", "page")

app/views.py
from django.db.models import QuerySet
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response, redirect, render
from django.views import generic

from app.forms import BookForm
from app.models import Book

# 既存のDjango Viewを使うやり方
class IndexView(generic.ListView):
    template_name = "app/book_list.html"

    def get_queryset(self):
        return Book.objects.all().order_by("id")


class DetailView(generic.DetailView):
    model = Book
    # template 名も自動で、book_detail.html が選ばれる


# 原始的やり方
def book_list(request):
    books: QuerySet[Book] = Book.objects.all().order_by("id")
    return render_to_response("app/book_list.html", {"book_list": books})


def book_edit(request, book_id=None):
    if book_id:  # book_id が指定されている (修正時)
        book: Book = get_object_or_404(Book, pk=book_id)
    else:  # book_id が指定されていない (追加時)
        book: Book = Book()

    # 既存Bookの取得
    if request.method == "POST":
        form: BookForm = BookForm(request.POST, instance=book)
        if form.is_valid():
            # book = form.save(commit=False)  # commit=False にするとDBにSaveされない
            # # なにかbookを編集する
            # book.save()

            # ModelFormからModel.save_m2m()を内部で呼び出して保存される
            form.save()
            return redirect("app:book_list")

    else:  # GET
        form = BookForm(instance=book)

    return render(request, "app/book_edit.html", {"form": form, "book_id": book_id})


def book_del(request, book_id):
    book: Book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect("app:book_list")


def other(request):
    return HttpResponse("ただのレスポンス")

templates/app/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}

<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  {% block extra_css %}{% endblock %}
  <title>{% block title %}My books{% endblock %}</title>
</head>
<body>
<div class="container">
  {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

templates/app/book_detail.html
{% extends "app/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の詳細{% endblock title %}

{% block content %}
  <h4 class="mt-4 mb-5 border-bottom">書籍の詳細</h4>

  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">書籍名</th>
      <th scope="col">出版社</th>
      <th scope="col">ページ数</th>
      <th scope="col">操作</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <th scope="row">{{ book.id }}</th>
      <td>{{ book.name }}</td>
      <td>{{ book.publisher }}</td>
      <td>{{ book.page }}</td>
      <td>
        <a href="{% url 'app:book_edit' book_id=book.id %}" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'app:book_del' book_id=book.id %}" class="btn btn-outline-danger btn-sm">削除</a>
      </td>
    </tr>
    </tbody>
  </table>

  <a href="{% url 'app:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

templates/app/book_edit.html
{% extends "app/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
  <h4 class="mt-4 mb-5 border-bottom">書籍の編集</h4>
  {% if book_id %}
    <form action="{% url 'app:book_edit' book_id=book_id %}" method="post">
  {% else %}
    <form action="{% url 'app:book_add' %}" method="post">
  {% endif %}

    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}

    <div class="form-group row">
      <div class="offset-md-3 col-md-9">
        <button type="submit" class="btn btn-primary">送信</button>
      </div>
    </div>
  </form>
  <a href="{% url 'app:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>

{% endblock content %}

templates/app/book_list.html
{% extends "app/base.html" %}

{% block title %}書籍の一覧{% endblock title %}

{% block content %}
  <h4 class="mt-4 border-bottom">書籍の一覧</h4>
  <a href="{% url 'app:book_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">書籍名</th>
      <th scope="col">出版社</th>
      <th scope="col">ページ数</th>
      <th scope="col">操作</th>
    </tr>
    </thead>
    <tbody>
    {% for book in book_list %}
      <tr>
        <th scope="row">{{ book.id }}</th>
        <td><a href={% url 'app:book_detail' pk=book.id %}>{{ book.name }}</a></td>
        <td>{{ book.publisher }}</td>
        <td>{{ book.page }}</td>
        <td>
          <a href="{% url 'app:book_edit' book_id=book.id %}" class="btn btn-outline-primary btn-sm">修正</a>
          <a href="{% url 'app:book_del' book_id=book.id %}" class="btn btn-outline-danger btn-sm">削除</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}